import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import { clientEnv } from "@/config/env";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

const googleSans = LocalFont({
  src: "../../public/fonts/google_sans.ttf",
  variable: "--font-google-sans",
  display: "auto",
});

export const metadata: Metadata = {
  title: clientEnv.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${googleSans.className} antialiased`}>{children}</body>
      <Toaster className={cn(googleSans.className, "font-medium")} />
    </html>
  );
}
